# This yaml file has been adapted from https://github.com/jdblischak/smk-simple-slurm
cluster:
  sbatch
    --partition=cpu_p
    --qos=cpu_normal
    --nice=10000
    -t 24:00:00
    -c 2
    --mem=10G
    --job-name=$outputfolder-{rule}-{wildcards}
    --output=$logdir/{rule}/{rule}-{wildcards}-%j.out
    --error=$logdir/{rule}/{rule}-{wildcards}-%j.err
default-resources:
  - partition=cpu_p
  - qos=cpu_normal
  - mem_mb=100000
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 60
jobs: 20
keep-going: True
printshellcmds: True
scheduler: greedy
use-conda: True
